sudo: required

services:
  - docker

branches:
  only:
  - master

before_install:
  - docker build -t misterq/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run misterq/react-test npm test -- --coverage

after_success:
  - docker build -t misterq/multi-client ./client
  - docker build -t misterq/multi-nginx ./nginx
  - docker build -t misterq/multi-server ./server
  - docker build -t misterq/multi-worker ./worker

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take those images and push them to docker hub
  - docker push misterq/multi-client
  - docker push misterq/multi-nginx
  - docker push misterq/multi-server
  - docker push misterq/multi-worker

  